// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// Next.js uses .env.local — load it explicitly for Prisma CLI
import { config } from "dotenv";
config({ path: ".env.local", override: true });

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (db push, migrate) memerlukan koneksi direct (bukan pooler)
    // DIRECT_URL = port 5432, DATABASE_URL = port 6543 (Supabase pooler)
    url: env("DIRECT_URL"),
  },
});
